### ISSUE TITLE
Fallback material style

### ISSUE THREAD

**Issue by DontTazeMeBros** [johannesjo/angular-material-css-vars#1]
Is there a way to use a set material style as a "fallback"?

i.e. @import '~@angular/material/prebuilt-themes/deeppurple-amber.css';

there already seems to be some kind of fallback because there is a light blue color that shows before my themeService has time to change it to the correct color. Didn't know if there was a way to override that with default theme

**Comment by johannesjo** [comment]
are two ways to set the default fallback theme. One is using the `mat-css-palette-defaults` mixin.
```scss
@import '../projects/material-css-vars/src/lib/public-util';
@import '../projects/material-css-vars/src/lib/main';

@include initMaterialCssVars();

@include mat-css-set-palette-defaults($mat-light-blue, 'primary');
@include mat-css-set-palette-defaults($mat-pink, 'accent');
@include mat-css-set-palette-defaults($mat-red, 'warn');
```
The other is to include your own variables for [$mat-css-default-light-theme](https://github.com/johannesjo/angular-material-css-vars/blob/master/projects/material-css-vars/src/lib/_variables.scss).
```scss
@import '../projects/material-css-vars/src/lib/main';

$mat-css-default-light-theme: map-merge(
  // if you don't want to enter ALL the properties
  $mat-css-default-light-theme,
  (
  --palette-primary-50: _mat-css-hex-to-rgb(#e1f5fe),
  --palette-primary-100: _mat-css-hex-to-rgb(#b3e5fc),
  --palette-primary-200: _mat-css-hex-to-rgb(#81d4fa),
  --palette-primary-300: _mat-css-hex-to-rgb(#4fc3f7),
  --palette-primary-400: _mat-css-hex-to-rgb(#29b6f6),
  --palette-primary-500: _mat-css-hex-to-rgb(#03a9f4),
  // ...
  )
);

@include initMaterialCssVars();

```

**Comment by clark-stevenson** [comment]
How would you handle a case where:


- If `.isLightTheme` then `@include mat-css-set-palette-defaults($mat-black, 'primary')`
- If `.isDarkTheme` then `@include mat-css-set-palette-defaults($mat-white, 'primary')`

Thanks!

**Comment by johannesjo** [comment]
@clark-stevenson this case is not covered yet. But you could use to implement it via a custom solution instead of  `initMatTheme()? 
https://github.com/johannesjo/angular-material-css-vars/blob/master/projects/material-css-vars/src/lib/_main.scss

**Comment by drimlike** [comment]
@johannesjo thanks for those details! I'm struggling a bit to get this done tho!

This is the main SCSS file we currently have:

```
// theme
@import '~angular-material-css-vars/public-util';
@import '~angular-material-css-vars/main';

// default dark/light theming
$mat-css-dark-theme-selector: '.isDarkTheme';
$mat-css-light-theme-selector: '.isLightTheme';

// init theme defaults
@import 'custom/mat-colors';
@include initMaterialCssVars();

@include mat-css-set-palette-defaults($mat-black, 'primary');
@include mat-css-set-palette-defaults($mat-teal, 'accent');
@include mat-css-set-palette-defaults($mat-red, 'warn');
```

FYI, the `@import 'custom/mat-colors';` contains the `$mat-black` and `$mat-white` colors missing in material and needed for our project.

We would like to have something like the below, but not sure how to do that.

```
...
@include mat-css-set-palette-defaults($mat-black, 'primary');

/* IF .isDarkTheme then use this value */
@include mat-css-set-palette-defaults($mat-white, 'primary');
...
```

I know the code cannot be done this way but it's to explain the concept.
Will this double the size of the css output? Is it even do-able?

I hope it makes sense. Thanks in advance for your feedback.

**Comment by picc09** [comment]
@drimlike currently the plugin manages properly only the light theme.
The problem is the miss declaration of background and foreground color tables for dark theme.
You can find these tables in `_variables.scss`.
I too use this project and for this problem I had to make a deep change.
I hope to help you and @johannesjo sharing my work.

First of all I split the background and foreground table into background-color, background-alpha, foreground-color and foreground-alpha:

My `_foreground.scss`. 
Some colours are commented, because you have to keep the original of Material. 
Moreover, I inherit the colors directly from the global variables.

```scss
$_mat-css-light-theme-foreground: (
        //base: _mat-css-to-rgb-list(black),
        divider: _mat-css-to-rgb-list($dark-dividers),
        dividers: _mat-css-to-rgb-list($dark-dividers),
        disabled: _mat-css-to-rgb-list($dark-disabled-text),
        disabled-button: _mat-css-to-rgb-list(black),
        disabled-text: _mat-css-to-rgb-list($dark-disabled-text),
        //elevation: _mat-css-to-rgb-list(black),
        hint-text: _mat-css-to-rgb-list($dark-disabled-text),
        secondary-text: _mat-css-to-rgb-list($dark-secondary-text),
        icon: _mat-css-to-rgb-list(black),
        icons: _mat-css-to-rgb-list(black),
        text: _mat-css-to-rgb-list(black),
        slider-min: _mat-css-to-rgb-list(black),
        slider-off: _mat-css-to-rgb-list(black),
        slider-off-active: _mat-css-to-rgb-list(black),
);
$_mat-css-light-theme-foreground-alpha: (
        divider: alpha($dark-dividers),
        dividers: alpha($dark-dividers),
        disabled: alpha($dark-disabled-text),
        disabled-button: 0.26,
        disabled-text: alpha($dark-disabled-text),
        hint-text: alpha($dark-disabled-text),
        secondary-text: alpha($dark-secondary-text),
        icon: 0.54
        icons: 0.54
        text: 0.87,
        slider-min: 0.87,
        slider-off: 0.26,
        slider-off-active: 0.38,
);

$_mat-css-dark-theme-foreground: (
        //base: _mat-css-to-rgb-list(white),
        divider: _mat-css-to-rgb-list($light-dividers),
        dividers: _mat-css-to-rgb-list($light-dividers),
        disabled: _mat-css-to-rgb-list($light-disabled-text),
        disabled-button: _mat-css-to-rgb-list(white),
        disabled-text: _mat-css-to-rgb-list($light-disabled-text),
        //elevation: _mat-css-to-rgb-list(black),
        hint-text: _mat-css-to-rgb-list($light-disabled-text),
        secondary-text: _mat-css-to-rgb-list($light-secondary-text),
        icon: _mat-css-to-rgb-list(white),
        icons: _mat-css-to-rgb-list(white),
        text: _mat-css-to-rgb-list(white),
        slider-min: _mat-css-to-rgb-list(white),
        slider-off: _mat-css-to-rgb-list(white),
        slider-off-active: _mat-css-to-rgb-list(white),
);
$_mat-css-dark-theme-foreground-alpha: (
        divider: alpha($light-dividers),
        dividers: alpha($light-dividers),
        disabled: alpha($light-disabled-text),
        disabled-button: 0.3,
        disabled-text: alpha($light-disabled-text),
        hint-text: alpha($light-disabled-text),
        secondary-text: alpha($light-secondary-text),
        slider-off: 0.3,
        slider-off-active: 0.3,
);
```

My `background.scss`
```scss
$_mat-css-light-theme-background: (
  status-bar: _mat-css-to-rgb-list(map_get($mat-grey, 300)),
  app-bar: _mat-css-to-rgb-list(map_get($mat-grey, 100)),
  background: map_get($mat-grey, 50),
  hover: _mat-css-to-rgb-list(black),
  card: _mat-css-to-rgb-list(white),
  dialog: _mat-css-to-rgb-list(white),
  disabled-button: _mat-css-to-rgb-list(black),
  raised-button: _mat-css-to-rgb-list(white),
  focused-button: _mat-css-to-rgb-list($dark-focused),
  selected-button: _mat-css-to-rgb-list(map_get($mat-grey, 300)),
  selected-disabled-button: _mat-css-to-rgb-list(map_get($mat-grey, 400)),
  disabled-button-toggle: _mat-css-to-rgb-list(map_get($mat-grey, 200)),
  unselected-chip: _mat-css-to-rgb-list(map_get($mat-grey, 300)),
  disabled-list-option: _mat-css-to-rgb-list(map_get($mat-grey, 200)),
);
$_mat-css-light-theme-background-alpha: (
  hover: 0.04,
  disabled-button: 0.12,
  focused-button: alpha($dark-focused),
);

$_mat-css-dark-theme-background: (
  status-bar: _mat-css-to-rgb-list(black),
  app-bar: _mat-css-to-rgb-list(map_get($mat-grey, 900)),
  background: _mat-css-to-rgb-list(#303030),
  hover: _mat-css-to-rgb-list(white),
  card: _mat-css-to-rgb-list(map_get($mat-grey, 800)),
  dialog: _mat-css-to-rgb-list(map_get($mat-grey, 800)),
  disabled-button: _mat-css-to-rgb-list(white),
  raised-button: _mat-css-to-rgb-list(map-get($mat-grey, 800)),
  focused-button: _mat-css-to-rgb-list($light-focused),
  selected-button: _mat-css-to-rgb-list(map_get($mat-grey, 900)),
  selected-disabled-button: _mat-css-to-rgb-list(map_get($mat-grey, 800)),
  disabled-button-toggle: _mat-css-to-rgb-list(black),
  unselected-chip: _mat-css-to-rgb-list(map_get($mat-grey, 700)),
  disabled-list-option: _mat-css-to-rgb-list(black),
);
$_mat-css-dark-theme-background-alpha: (
  hover: 0.04,
  disabled-button: 0.12,
  focused-button: alpha($light-focused),
);
```

Now the complex... this is my set of helpers, I use it to create the palettes in compact and fast way. 
**Keep in mind**, in my project I change all variable names to generate more compressed css.

```scss
$mat-css-hue-values: (50, 100, 200, 300, 400, 500, 600, 700, 800, 900, A100, A200, A400, A700);

@function _mat-css-color-palette($mat-palette: $mat-gray) {
  $vars-map: ();
  @each $hue in $mat-css-hue-values {
    $map-value: map_get($mat-palette, $hue);
    $vars-map: map_merge($vars-map, ($hue: _mat-css-to-rgb-list($map-value)));
  }
  @return $vars-map;
}

@function _mat-css-contrast-color-palette($mat-palette: $mat-gray) {
  $contrast-map: map_get($mat-palette, contrast);
  $vars-map: ();
  @each $hue in $mat-css-hue-values {
    $contrast-color: map_get($contrast-map, $hue);
    $map-value: if(($contrast-color == $light-primary-text), var(--lpt), var(--dpt));
    $vars-map: map_merge($vars-map, ($hue: $map-value));
  }
  @return $vars-map;
}

@function _mat-css-variable-map($result, $map, $prefix, $suffix: null) {
  @each $prop, $value in $map {
    $var-name: "--#{$prefix}-#{$prop}";
    @if $suffix {
      $var-name: "#{$var-name}-#{$suffix}"
    }
    $result: map_merge($result, ($var-name: $value));

  }
  @return $result;
}

@function _mat-css-theme-map($map, $prefix, $merge: ()) {
  @each $prop, $value in $map {
    $merge: map_merge($merge, ($prop: var(unquote("--#{$prefix}-#{$prop}"))));
  }
  @return $merge;
}
```

And now on the stage the new `_variables.scss`.
`--dpt` means `dark primary text` and obviously `--lpt` means `light primary text`.
Working on this will be given the opportunity to inherit the colors of Material.

```scss
$mat-css-default-light-theme: (
  --dpt: _mat-css-to-rgb-list($dark-primary-text),
  --lpt: _mat-css-to-rgb-list($light-primary-text),
);

$_mat-css-primary: _mat-css-color-palette();
$_mat-css-accent: _mat-css-color-palette();
$_mat-css-warn: _mat-css-color-palette();
$_mat-css-primary-contrast: _mat-css-contrast-color-palette();
$_mat-css-accent-contrast: _mat-css-contrast-color-palette();
$_mat-css-warn-contrast: _mat-css-contrast-color-palette();

// p [l = light | d = dark] [p = primary | a = accent | w = warn | b = background | f = foreground] [c = contrast]?
$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-primary, 'plp');
$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-primary-contrast, 'plpc');

$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-accent, 'pla');
$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-accent-contrast, 'plac');

$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-warn, 'plw');
$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-warn-contrast, 'plwc');

$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-light-theme-background, 'plb');
$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-light-theme-background-alpha, 'plb', 'a');

$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-light-theme-foreground, 'plf');
$mat-css-default-light-theme: _mat-css-variable-map($mat-css-default-light-theme, $_mat-css-light-theme-foreground-alpha, 'plf', 'a');

$mat-css-contrast-light: _mat-css-theme-map($_mat-css-primary-contrast, 'plpc');
$mat-css-light-primary: _mat-css-theme-map($_mat-css-primary, 'plp', (contrast: $mat-css-contrast-light));

$mat-css-contrast-light-accent: _mat-css-theme-map($_mat-css-accent-contrast, 'plac');
$mat-css-light-accent: _mat-css-theme-map($_mat-css-accent, 'pla', (contrast: $mat-css-contrast-light-accent));

$mat-css-contrast-light-warn: _mat-css-theme-map($_mat-css-warn-contrast, 'plwc');
$mat-css-light-warn: _mat-css-theme-map($_mat-css-warn, 'plw', (contrast: $mat-css-contrast-light-warn));

$mat-css-light-background: _mat-css-theme-map($_mat-css-light-theme-background, 'plb');
$mat-css-light-foreground: _mat-css-theme-map($_mat-css-light-theme-foreground, 'plf', (base: black, elevation: black));
$mat-css-dark-background: _mat-css-theme-map($_mat-css-dark-theme-background, 'pdb');
$mat-css-dark-foreground: _mat-css-theme-map($_mat-css-dark-theme-foreground, 'pdf', (base: white, elevation: black));
```

Now you say, *oh hell, how are you gonna use all this?*
First of all the pimp the `mat-color` for the new maps and after create some helper function to use the colors...
```scss
@function _mat-css-has-alpha($name, $prefix, $alpha-map) {
  $index: str-index($name, $prefix);
  @if ($index == null) {
    @return false;
  }
  $color-name: str-slice($name, $index + 6, -2);
  @return map_has_key($alpha-map, $color-name);
}

// main overwrite to make it all work
@function mat-color($palette, $hue: default, $opacity: null) {
  @if type-of($hue) == number and $hue >= 0 and $hue <= 1 {
    @return mat-color($palette, default, $hue);
  }

  $color: map-get($palette, $hue);

  @if type-of($color) == color {
    @return rgba($color, if($opacity == null, opacity($color), $opacity));
  } @else if $opacity == null {
    $is-light-bg-alpha: _mat-css-has-alpha($color, '--plb-', $_mat-css-light-theme-background-alpha);
    $is-dark-bg-alpha: _mat-css-has-alpha($color, '--pdb-', $_mat-css-dark-theme-background-alpha);
    $is-light-fg-alpha: _mat-css-has-alpha($color, '--plf-', $_mat-css-light-theme-foreground-alpha);
    $is-dark-fg-alpha: _mat-css-has-alpha($color, '--plf-', $_mat-css-dark-theme-foreground-alpha);
    @if $is-light-bg-alpha or $is-dark-bg-alpha or $is-light-fg-alpha or $is-dark-fg-alpha {
      @return rgba($color, _mat-css-str-replace($color, ')', '-a)'));
    } @else {
      @return rgba($color, 1);
    }
  } @else {
    @return rgba($color, $opacity);
  }
}

// @return {color}
@function _mat-css-hue-color($hue: 500, $opacity: null, $palette: 'primary', $contrast: false) {
  $palette_: $mat-css-light-primary;
  @if ($contrast == true) {
    @if ($palette=='primary') {
      $palette_: $mat-css-contrast-light;
    } @else if ($palette=='accent') {
      $palette_: $mat-css-contrast-light-accent;
    } @else if ($palette=='warn') {
      $palette_: $mat-css-contrast-light-warn;
    } @else {
      @error 'Invalid contrast palette';
    }
  } @else {
    @if ($palette=='primary') {
      $palette_: $mat-css-light-primary;
    } @else if ($palette=='accent') {
      $palette_: $mat-css-light-accent;
    } @else if ($palette=='warn') {
      $palette_: $mat-css-light-warn;
    } @else {
      @error 'Invalid palette';
    }
  }

  @if (type-of($opacity) == number) {
    @return _mat-css-rgba(map_get($palette_, $hue), $opacity);
  } @else {
    @return _mat-css-rgb(map_get($palette_, $hue));
  }
}

@mixin mat-css-variables($default-theme) {
  // init css variables
  @include _mat-css-root($default-theme);
}

@function mat-css-light-theme() {
  $primary: mat-palette($mat-css-light-primary);
  $accent: mat-palette($mat-css-light-accent);
  $warn: mat-palette($mat-css-light-warn);
  $theme: mat-light-theme($primary, $accent, $warn);
  @return map_merge($theme, (
          background: $mat-css-light-background,
          foreground: $mat-css-light-foreground,
  ));
}

@function mat-css-dark-theme() {
  $primary: mat-palette($mat-css-light-primary);
  $accent: mat-palette($mat-css-light-accent);
  $warn: mat-palette($mat-css-light-warn);
  $dark-theme: mat-dark-theme($primary, $accent, $warn);
  @return $dark-theme;
}

@mixin mat-css-init-theme($light-theme, $dark-theme) {
  @at-root {
    // NOTE: light theme is the default theme
    @include angular-material-theme($light-theme);
    @if $dark-theme-selector {
      #{$dark-theme-selector} {
        @include angular-material-theme($dark-theme);
      }
    }
  }
}

@function get-primary-color($hue, $contrast: false, $opacity: null) {
  @return _mat-css-hue-color($hue, $opacity, 'primary', $contrast);
}

@function get-accent-color($hue, $contrast: false, $opacity: null) {
  @return _mat-css-hue-color($hue, $opacity, 'accent', $contrast);
}

@function get-warn-color($hue, $contrast: false, $opacity: null) {
  @return _mat-css-hue-color($hue, $opacity, 'warn', $contrast);
}

@function get-background-color($hue, $opacity: null) {
  $palette: map-get($mat-css-light-theme, background);
  @return mat-color($palette, $hue, $opacity);
}

@function get-foreground-color($hue, $opacity: null) {
  $palette: map-get($mat-css-light-theme, foreground);
  @return mat-color($palette, $hue, $opacity);
}
```

I hope I've been helpful.
This code is currently in production, so if you have any problems making it work, ask.
Have fun!
