### ISSUE TITLE
Opacity Broken in mat-css-color utility

### ISSUE THREAD

**Issue by dflor003** [johannesjo/angular-material-css-vars#121]
## :ghost: Brief Description

The `mat-css-color` utility in `_public-util.scss` used to respect the `$opacity` parameter. However, it looks like, it no longer does this behavior.

After doing some investigation, it looks like the `$opacity` variable is no longer being passed to anything. It was removed in [this commit](https://github.com/johannesjo/angular-material-css-vars/blob/708feaf5d181101ad99f7b4fb37df83dd3359a47/projects/material-css-vars/src/lib/_public-util.scss#L8-L32) and [this commit](https://github.com/johannesjo/angular-material-css-vars/blob/5ad19beb675d70f025498873451d54bd0cbcb780/projects/material-css-vars/src/lib/_public-util.scss#L34-L38) is the last that I found that had the correct behavior.

The lines that were removed were these:

```scss
  @if (type-of($opacity) == number) {
    @return rgba($color, $opacity);
  } @else {
    @return rgb($color);
  }
```

Can that line be re-added in a future version?

## :pancakes: Action version

4.2.1

## Steps To Reproduce

1. Set the color of something using the following code:
```scss
@use 'angular-material-css-vars/public-util' as util;

.my-element {
  background-color: util.mat-css-color-accent(500, 0.3);
}
```
2. Inspect the generated CSS on the element in chrome dev tools

## :police_car: Expected behavior

Element CSS should be similar to the following:

```css
.my-element {
  background-color: rgba(var(--palette-accent-500), 0.3);
}
```

Actual behavior:

```css
.my-element {
  background-color: var(--palette-accent-500-rgb);
}
```
