### ISSUE TITLE
Problems with foreground base color 

### ISSUE THREAD

**Issue by picc09** [johannesjo/angular-material-css-vars#5]
For reasons I don't understand, sometimes the material team doesn't uses **mat-color**.
I found the following uses:

- `@mixin mat-ripple-theme($theme)`
- `@mixin mat-button-theme($theme)` -> `.mat-button-focus-overlay`
- `@mixin mat-chips-theme($theme)` -> `.mat-chip.mat-standard-chip` > `&::after`
- `@mixin mat-radio-theme($theme)` -> `.mat-ripple-element`
- `@mixin mat-checkbox-theme($theme)` -> `.mat-checkbox .mat-ripple-element`

I have no idea how to fix these, temporarily I created the next fix:

```scss
.mat-button-focus-overlay,
.mat-checkbox .mat-ripple-element,
.mat-chip.mat-standard-chip::after,
.mat-radio-button .mat-ripple-element {
  $foregroundTheme: map-get($mat-css-default-theme, foreground);
  $foregroundBaseColor: mat-color($foregroundTheme, base);
  background-color: $foregroundBaseColor;
}
```

and overwrite **mat-ripple-theme**
```scss
@mixin mat-ripple-theme($theme) {
  $foreground: map_get($theme, foreground);
  $foreground-base: map_get($foreground, base);

  .mat-ripple-element {
    // If the ripple color is resolves to a color *type*, we can use it directly, otherwise
    // (e.g. it resolves to a CSS variable) we fall back to using the color and setting an opacity.
    @if (type-of($foreground-base) == color) {
      background-color: rgba($foreground-base, $mat-ripple-color-opacity);
    }
    @else {
      background-color: mat-color($foreground, base);
      opacity: $mat-ripple-color-opacity;
    }
  }
}```

**Comment by johannesjo** [comment]
Hey! Thanks for digging into this. I'm not sure if I understand the underlying problem. Is it that the ripples are not as noticeable as they should be or is it something else? 

I noticed that the ripples for tabs and the elevated and flat buttons are barely noticeable. This might be a wrong default value or mis- mapping. For the primary colored buttons the default `.mat-ripple-element` `background-color` is always `rgba(255,255,255,0.1)` while we are using `rgba(var(--palette-primary-contrast-500), var(--palette-primary-contrast-500-alpha, 0.1))` which is a little bit darker than that. Setting the background to `rgba(255,255,255,0.1)` via the dev tools has no effect however.

Not sure I'll keep investigating. Let me know if you find out anything!

**Comment by picc09** [comment]
First of all, it is always possible to remove the runtime customization of foreground-base and fix the problem as for elevation (finally, I adopted this road and I hope it will be all right).
The problem exists only for ripples without color (slide-toggle false, custom ripples, default buttons), in these cases, the ripple is a white gradient instead of black gradient (light theme).
I want to focus your attention on WHITE GRADIENT, why white?
From what I understand (I'm not 100% sure), because it is the default color for the element, without a fix, you assign an invalid color (variable with list value) at the background.

**Comment by johannesjo** [comment]
I think I found the issue for the ripples. Problem is the opacity fallback, which stays in place even if the background-color is overwritten with an rgba value with its own alpha.

I'll continue to work on this tomorrow. Thanks for your input!

**Comment by johannesjo** [comment]
I published another fix. Correct me if I'm mistaken but I think we don't need this anymore, because they already seem to work as they should:
```scss
.mat-button-focus-overlay,
.mat-checkbox .mat-ripple-element,
.mat-chip.mat-standard-chip::after,
.mat-radio-button .mat-ripple-element {
  $foregroundTheme: map-get($mat-css-default-theme, foreground);
  $foregroundBaseColor: mat-color($foregroundTheme, base);
  background-color: $foregroundBaseColor;
}
```
