### ISSUE TITLE
mat-form-field-underline color

### ISSUE THREAD

**Issue by austenstone** [johannesjo/angular-material-css-vars#66]
## :ghost: Brief Description

The input fields don't have proper colors for `mat-form-field-underline`.

Look at these images and notice the underline color. (I am not interacting with the input)

Before
![image](https://user-images.githubusercontent.com/22425467/112322737-8a146c80-8c87-11eb-8796-7b3262e8e6d6.png)

After
![image](https://user-images.githubusercontent.com/22425467/112322556-63eecc80-8c87-11eb-8e69-12487e2f35bd.png)

## :pancakes: Action version

After updating 1.1.1 to 1.2.0

## :tophat: workflow configuration

Don't know what workflow configuration would mean.

## Steps To Reproduce

Use any input field inside a mat form field.

## :police_car: Expected behavior

Expected
![image](https://user-images.githubusercontent.com/22425467/112322771-91d41100-8c87-11eb-8111-f8461f6ee667.png)

See [Angular Material Input](https://material.angular.io/components/input/examples)
## :heavy_plus_sign: Additional context

This was okay before I updated to 1.2.0

```scss
@mixin mat-form-field-legacy-color($config-or-theme) {
    .mat-form-field-underline {
      background-color: $underline-color;
    }
}
```

`background-color: rgba(var(--palette-foreground-divider-dark), var(--palette-foreground-divider-dark-alpha, 0.7));`
