### ISSUE TITLE
vars not using rgba() in package release

### ISSUE THREAD

**Issue by negue** [johannesjo/angular-material-css-vars#7]
Hi,

just wanted to tryout but it doesn't add `rgba()` to the styles, I used the tutorial from the README.md.

Trying to figure it out, I tried the demo of this repo:
Example App CSS:
```css
.isDarkTheme .mat-toolbar.mat-primary {
    background: rgba(var(--palette-primary-500), 1);
    color: rgba(var(--palette-primary-contrast-500), 1);
}
```

in my app:
```css
.isDarkTheme .mat-toolbar.mat-primary {
    background: var(--palette-primary-500);
    color: var(--palette-primary-contrast-500);
}
```

is the release out of date or did I miss something?
